[project]
name = "medical-policy-decision-tree-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">3.13"
dependencies = [
    "google-cloud-aiplatform[adk,agent-engines]>=1.128.0",
    "google-genai>=1.51.0",
    "jupyterlab>=4.5.0",
    "pydantic>=2.12.4",
    "pymupdf4llm>=0.2.2",
]

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "medical_policy_decision_tree_agent"
source-exclude = [".git",".gitignore"]


[dependency-groups]
dev = [
    "black>=25.11.0",
]
